### ISSUE TITLE
Rapid API not returning states for selected country

### ISSUE THREAD

**Issue by Owoade** [LazerpayHQ/lazerpay-node-sdk#10]
![lazer](https://user-images.githubusercontent.com/63651250/197365910-b4d25379-8817-4818-8b45-e8ed7d59006b.PNG)
![lazer2](https://user-images.githubusercontent.com/63651250/197365912-e67edb67-cd26-4907-ab09-3a3d2baea942.PNG)

**Comment by kohasummons** [comment]
Hi @Owoade, thanks for raising the issue. Please, could you provide a brief description of the issue. Perhaps, what you were trying to do. What methods you were calling

**Comment by iamnotstatic** [comment]
> Hello there, I was trying to use the checkout link to make a test payment and the form field for state of residence wasn't returning the states for the selected country which in my case was Nigeria ![lazerpay](https://user-images.githubusercontent.com/63651250/201196303-8987a621-e618-4234-9bd7-4708fc38719d.PNG) After a little digging, I discovered that it was as a fault from the API as reported earlier. Thanks in anticipation as I await rectification.

Hi @Owoade, The issue has been resolved.
